#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

protected_branch="main"
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "Direct push to $protected_branch branch is not allowed. Please create a pull request instead."
    exit 1
fi
