name: Branch Protection Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  protect-main:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct pushes to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Direct pushes to main branch are not allowed"
          exit 1
